site_name: API документация
site_description: С помощью этого API вы можете создавать и искать пользователей, а также изменять информацию о них.

theme:
  name: material
  features:
    - navigation.expand

plugins:
  - search

nav:
  - Главная страница: index.md
  
  - API:
    - Что такое API: api/about-api.md

  - Doc-as-Code:
    - Git:
        - Что такое Git: doc-as-code/git/about-git.md
        - Команды Git: doc-as-code/git/teams-git.md

    - Создать сайт с MkDocs:
        - Описание: doc-as-code/mkdocs/create-site-with-mkdocs/description.md
        - Инструкция: doc-as-code/mkdocs/create-site-with-mkdocs/instruction.md

  - Регламенты поддержки:
      - Что нужно знать о поддержке: regulations-support/about-support.md

