site_name: API документация
site_description: С помощью этого API вы можете создавать и искать пользователей, а также изменять информацию о них.

theme:
  name: material
  features:
    - navigation.expand

plugins:
  - search

nav:
  - Главная: index.md
  - Описание API: Description.md
  - Начало работы:
      - Авторизация: Authorize.md
      - Отправить запрос: Try.md
  - Справочник API:
      - Операции с пользователями: Method.md
